#***************************************
# MODULE 1
# compute occupancy model on cluster
# 
#***************************************
# ==============================================================
# setwd("/home/reto/Documents/LOLA_BMS/Occupancy Model project/Occupancy_modellingNEWJUNE/OCC_results/countries_UNI_2000_sd_1/Anthocharis_cardamines")

setwd("~/Desktop/Apatura_iris/")

library(R2jags)

load(list.files()[grep(".RData",list.files())])

if (!file.exists("results/jagsoutput.Rdata")){

  modelnbr <- 1
  ni <- 15000
  nb <- 12500
  nt <- 5
  nch <- 3
  
  jags_model <- paste0("OCCmodel_",modelnbr,"_jagscript_tidev_zone.txt")
  analysis.par <- data.frame(parameters=c("species","country_of_flight","country","country_with_obs","year_toget","min_nbr_year","nbr_per_gridcell","ni","nb","nt","jags_model"),values=c(species,country_of_flight,country,paste(country_with_obs,collapse=","),year_toget,min_nbr_year,nbr_siteperGRID,ni,nb,nt,jags_model))
  y <- c(1:nyear)
  data <- list("M", "y", "nsite", "nvisit", "nyear", "sumX", "sumX2", "maxyear","NM","TL","psi_min","psi_max","bnm_min","bnm_max","btl_min","btl_max","bphi_min","bphi_max","bgam_min","bgam_max","tidev_mat_zone","SUITABLE")

  # ignore warning generated by JAGS: "ni, nt and nt not used in model"
  # (2) Starting values
  warn <- -1
  zst <- apply(M,c(1,3),max,na.rm=TRUE)  	# inits per site and year; c(1,3) means: inits for dimension 1-3 = site, visit and year
  warn <- 0
  zst[zst==(-Inf)] <- 1 			# inits for -infinite: 1
  zst[zst==(Inf)]  <- 1			# inits for infinite : 1
  pst <- rep(0.5, nyear) 
  
  # set initial value for each model structure
  
  inits <- function() {list (z=zst, alpha.p=rep(runif(1, -2, 2), nyear), 
                             muphi1=rnorm(1), betaphi1=rnorm(1), sigmaphi1=runif(1,0,5),
                             muphi2=rnorm(1), betaphi2=rnorm(1), sigmaphi2=runif(1,0,5),
                             muphi3=rnorm(1), betaphi3=rnorm(1), sigmaphi3=runif(1,0,5),
                             muphi4=rnorm(1), betaphi4=rnorm(1), sigmaphi4=runif(1,0,5),
                             mugam1=rnorm(1), betagam1=rnorm(1), sigmagam1=runif(1,0,5),
                             mugam2=rnorm(1), betagam2=rnorm(1), sigmagam2=runif(1,0,5),
                             mugam3=rnorm(1), betagam3=rnorm(1), sigmagam3=runif(1,0,5),
                             mugam4=rnorm(1), betagam4=rnorm(1), sigmagam4=runif(1,0,5),
                             nm.p=runif(1,-2,2),tl.p=runif(1,-2,2))}
  
  parameters <- c("z", "psi.fs", "psi.fs_z", "psi.suit_z", "phi.suit_z", "gam.suit_z",
                  "bnm.p", "btl.p", "alpha.p",
                  "muphi1", "muphi2", "muphi3", "muphi4",
                  "sigmaphi1_2", "sigmaphi2_2", "sigmaphi3_2", "sigmaphi4_2",
                  "betaphi1", "betaphi2", "betaphi3", "betaphi4",
                  "beta.phi1", "beta.phi2", "beta.phi3", "beta.phi4",
                  "mugam1", "mugam2", "mugam3", "mugam4",
                  "sigmagam1_2", "sigmagam2_2", "sigmagam3_2", "sigmagam4_2",
                  "betagam1", "betagam2", "betagam3", "betagam4",
                  "beta.gam1", "beta.gam2", "beta.gam3", "beta.gam4")



jags_fit <- function (data, inits, parameters.to.save, model.file = "model.bug", 
    n.chains = 3, n.iter = 2000, n.burnin = floor(n.iter/2), 
    n.thin = max(1, floor((n.iter - n.burnin)/1000)), DIC = TRUE, 
    working.directory = NULL, jags.seed = 123, refresh = n.iter/50, 
    progress.bar = "text", digits = 4, RNGname = c("Wichmann-Hill", 
        "Marsaglia-Multicarry", "Super-Duper", "Mersenne-Twister")) 
{
    if (!is.null(working.directory)) {
        working.directory <- path.expand(working.directory)
        savedWD <- getwd()
        setwd(working.directory)
        on.exit(setwd(savedWD))
    }
    else {
        savedWD <- getwd()
        working.directory <- savedWD
    }
    if (is.character(data) && length(data) == 1 && regexpr("\\.txt$", 
        data) > 0) {
        if (all(basename(data) == data)) {
            fn2 <- file.path(working.directory, data)
            if (normalizePath(fn2) != normalizePath(data)) {
                try(file.copy(fn2, data, overwrite = TRUE))
            }
        }
        if (!file.exists(data)) {
            stop("File", data, "does not exist")
        }
        if (file.info(data)["size"] == 0) {
            stop("Empty data file ", data)
        }
        e <- new.env()
        eval(parse(data), e)
        data <- as.list(e)
    }
    else if (is.character(data) || (is.list(data) && all(sapply(data, 
        is.character)))) {
        dlist <- lapply(as.list(data), get, envir = parent.frame(1))
        names(dlist) <- unlist(data)
        data <- dlist
    }
    else if (!is.list(data)) {
        stop("data must be a character vector of object names, a list of object names, or a list of objects")
    }
    if (is.function(model.file)) {
        temp <- tempfile("model")
        temp <- if (is.R() || .Platform$OS.type != "windows") {
            paste(temp, "txt", sep = ".")
        }
        else {
            gsub("\\.tmp$", ".txt", temp)
        }
        write.model(model.file, con = temp, digits = digits)
        model.file <- gsub("\\\\", "/", temp)
        if (!is.R()) 
            on.exit(file.remove(model.file), add = TRUE)
    }
    if (DIC) {
        parameters.to.save <- c(parameters.to.save, "deviance")
        load.module("dic", quiet = TRUE)
    }
    if (n.burnin > 0) {
        n.adapt <- n.burnin
    }
    else {
        n.adapt <- 100
    }
    if (!missing(inits) && !is.function(inits) && !is.null(inits) && 
        (length(inits) != n.chains)) {
        stop("Number of initialized chains (length(inits)) != n.chains")
    }
    RNGname <- match.arg(RNGname)
    if (RNGname %in% c("Wichmann-Hill", "Marsaglia-Multicarry", 
        "Super-Duper", "Mersenne-Twister")) {
        RNGname <- paste("base::", RNGname, sep = "")
    }
    else {
        stop("The name of the RNG is not correctly provided!")
    }
    load.module("glm")
    init.values <- vector("list", n.chains)
    if (missing(inits)) {
        for (i in 1:n.chains) {
            init.values[[i]]$.RNG.name <- RNGname
            init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                1])
        }
    }
    else if (is.null(inits)) {
        for (i in 1:n.chains) {
            init.values[[i]]$.RNG.name <- RNGname
            init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                1])
        }
    }
    else if (is.function(inits)) {
        if (any(names(formals(inits)) == "chain")) {
            for (i in 1:n.chains) {
                init.values[[i]] <- inits(chain = i)
                init.values[[i]]$.RNG.name <- RNGname
                init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                  1])
            }
        }
        else {
            for (i in 1:n.chains) {
                init.values[[i]] <- inits()
                init.values[[i]]$.RNG.name <- RNGname
                init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                  1])
            }
        }
    }
    else {
        if (!is.list(inits)) {
            stop("Invalid inits")
        }
        if (length(inits) != n.chains) {
            stop("Number of initialized chains (length(inits)) != n.chains")
        }
        for (i in 1:n.chains) {
            init.values[[i]] <- inits[[i]]
            init.values[[i]]$.RNG.name <- RNGname
            init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                1])
        }
    }
    m <- jags.model(model.file, data = data, inits = init.values, 
        n.chains = n.chains, n.adapt = 0)
    adapt(m, n.iter = n.adapt, by = refresh, progress.bar = progress.bar, 
        end.adaptation = TRUE)
    samples <- coda.samples(model = m, variable.names = parameters.to.save, 
        n.iter = (n.iter - n.burnin), thin = n.thin, by = refresh, 
        progress.bar = progress.bar)
    fit <- mcmc2bugs(samples, model.file = model.file, program = "jags", 
        DIC = DIC, DICOutput = NULL, n.iter = n.iter, n.burnin = n.burnin, 
        n.thin = n.thin)[c("sims.array","sims.list","summary","pD","DIC")]
    out <- list(model = m, BUGSoutput = fit, parameters.to.save = parameters.to.save, 
        model.file = model.file, n.iter = n.iter, DIC = DIC)
    class(out) <- "rjags"
    return(out)
}
  environment(jags_fit) <- environment(jags)
  
  set.seed(1234)
  
  out <- jags_fit(data, inits, parameters, jags_model, n.chains=nch, n.iter = ni, n.thin=nt, n.burnin=nb, DIC=TRUE, working.directory=NULL)
  
  write.csv(out$BUGSoutput$summary, file = jobnameout)
  write.csv(analysis.par, file = paste(modelnbr,"AnalysisParameters.csv",sep="_"), row.names=F)
  save(out,file="jagsoutput.Rdata")
  print(gc())

} else {
  
  load("results/jagsoutput.Rdata")
  
  modelnbr <- 1
  ni <- 15000
  nb <- 12500
  nt <- 5
  nch <- 3
  
  jags_model <- paste0("OCCmodel_",modelnbr,"_jagscript_tidev_zone.txt")
  analysis.par <- data.frame(parameters=c("species","country_of_flight","country","country_with_obs","year_toget","min_nbr_year","nbr_per_gridcell",
                                          "ni","nb","nt","jags_model"),values=c(species,country_of_flight,country,paste(country_with_obs,collapse=","),
                                                                                year_toget,min_nbr_year,nbr_siteperGRID,ni+15000,nb+15000,nt,jags_model))
  y <- c(1:nyear)
  data <- list("M", "y", "nsite", "nvisit", "nyear", "sumX", "sumX2", "maxyear","NM","TL","psi_min","psi_max","bnm_min","bnm_max","btl_min","btl_max","bphi_min","bphi_max","bgam_min","bgam_max","tidev_mat_zone","SUITABLE")
  
  # (2) Starting values
  inits <- vector("list", nch)
  
  for (i in 1:nch){
    iter <- dim(out$BUGSoutput$sims.array)[1]
    chain.n <- i
    inits1 <- list(z = matrix(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,2)=="z["],ncol=15),
    alpha.p = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,7)=="alpha.p"],
    muphi1 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="muphi1"],
    muphi2 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="muphi2"],
    muphi3 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="muphi3"],
    muphi4 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="muphi4"],
    mugam1 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="mugam1"],
    mugam2 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="mugam2"],
    mugam3 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="mugam3"],
    mugam4 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,6)=="mugam4"],
    betaphi1 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betaphi1"],
    betaphi2 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betaphi2"],
    betaphi3 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betaphi3"],
    betaphi4 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betaphi4"],
    betagam1 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betagam1"],
    betagam2 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betagam2"],
    betagam3 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betagam3"],
    betagam4 = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,8)=="betagam4"],
    sigmaphi1 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmaphi1"]),
    sigmaphi2 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmaphi2"]),
    sigmaphi3 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmaphi3"]),
    sigmaphi4 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmaphi4"]),
    sigmagam1 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmagam1"]),
    sigmagam2 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmagam2"]),
    sigmagam3 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmagam3"]),
    sigmagam4 = sqrt(out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,9)=="sigmagam4"]),
    bnm.p = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,5)=="bnm.p"],
    btl.p = out$BUGSoutput$sims.array[iter,chain.n,substring(names(out$BUGSoutput$sims.array[iter,chain.n,]),1,5)=="btl.p"])
    
    inits[[chain.n]] <- inits1
  }
  
   parameters <- c("z", "psi.fs", "psi.fs_z", "psi.suit_z", "phi.suit_z", "gam.suit_z",
                  "bnm.p", "btl.p", "alpha.p",
                  "muphi1", "muphi2", "muphi3", "muphi4",
                  "sigmaphi1_2", "sigmaphi2_2", "sigmaphi3_2", "sigmaphi4_2",
                  "betaphi1", "betaphi2", "betaphi3", "betaphi4",
                  "beta.phi1", "beta.phi2", "beta.phi3", "beta.phi4",
                  "mugam1", "mugam2", "mugam3", "mugam4",
                  "sigmagam1_2", "sigmagam2_2", "sigmagam3_2", "sigmagam4_2",
                  "betagam1", "betagam2", "betagam3", "betagam4",
                  "beta.gam1", "beta.gam2", "beta.gam3", "beta.gam4")
  
  jags_fit <- function (data, inits, parameters.to.save, model.file = "model.bug", 
                        n.chains = 3, n.iter = 2000, n.burnin = floor(n.iter/2), 
                        n.thin = max(1, floor((n.iter - n.burnin)/1000)), DIC = TRUE, 
                        working.directory = NULL, jags.seed = 123, refresh = n.iter/50, 
                        progress.bar = "text", digits = 4, RNGname = c("Wichmann-Hill", 
                                                                       "Marsaglia-Multicarry", "Super-Duper", "Mersenne-Twister")) 
  {
    if (!is.null(working.directory)) {
      working.directory <- path.expand(working.directory)
      savedWD <- getwd()
      setwd(working.directory)
      on.exit(setwd(savedWD))
    }
    else {
      savedWD <- getwd()
      working.directory <- savedWD
    }
    if (is.character(data) && length(data) == 1 && regexpr("\\.txt$", 
                                                           data) > 0) {
      if (all(basename(data) == data)) {
        fn2 <- file.path(working.directory, data)
        if (normalizePath(fn2) != normalizePath(data)) {
          try(file.copy(fn2, data, overwrite = TRUE))
        }
      }
      if (!file.exists(data)) {
        stop("File", data, "does not exist")
      }
      if (file.info(data)["size"] == 0) {
        stop("Empty data file ", data)
      }
      e <- new.env()
      eval(parse(data), e)
      data <- as.list(e)
    }
    else if (is.character(data) || (is.list(data) && all(sapply(data, 
                                                                is.character)))) {
      dlist <- lapply(as.list(data), get, envir = parent.frame(1))
      names(dlist) <- unlist(data)
      data <- dlist
    }
    else if (!is.list(data)) {
      stop("data must be a character vector of object names, a list of object names, or a list of objects")
    }
    if (is.function(model.file)) {
      temp <- tempfile("model")
      temp <- if (is.R() || .Platform$OS.type != "windows") {
        paste(temp, "txt", sep = ".")
      }
      else {
        gsub("\\.tmp$", ".txt", temp)
      }
      write.model(model.file, con = temp, digits = digits)
      model.file <- gsub("\\\\", "/", temp)
      if (!is.R()) 
        on.exit(file.remove(model.file), add = TRUE)
    }
    if (DIC) {
      parameters.to.save <- c(parameters.to.save, "deviance")
      load.module("dic", quiet = TRUE)
    }
    if (n.burnin > 0) {
      n.adapt <- n.burnin
    }
    else {
      n.adapt <- 100
    }
    if (!missing(inits) && !is.function(inits) && !is.null(inits) && 
        (length(inits) != n.chains)) {
      stop("Number of initialized chains (length(inits)) != n.chains")
    }
    RNGname <- match.arg(RNGname)
    if (RNGname %in% c("Wichmann-Hill", "Marsaglia-Multicarry", 
                       "Super-Duper", "Mersenne-Twister")) {
      RNGname <- paste("base::", RNGname, sep = "")
    }
    else {
      stop("The name of the RNG is not correctly provided!")
    }
    load.module("glm")
    init.values <- vector("list", n.chains)
    if (missing(inits)) {
      for (i in 1:n.chains) {
        init.values[[i]]$.RNG.name <- RNGname
        init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                                                         1])
      }
    }
    else if (is.null(inits)) {
      for (i in 1:n.chains) {
        init.values[[i]]$.RNG.name <- RNGname
        init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                                                         1])
      }
    }
    else if (is.function(inits)) {
      if (any(names(formals(inits)) == "chain")) {
        for (i in 1:n.chains) {
          init.values[[i]] <- inits(chain = i)
          init.values[[i]]$.RNG.name <- RNGname
          init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                                                           1])
        }
      }
      else {
        for (i in 1:n.chains) {
          init.values[[i]] <- inits()
          init.values[[i]]$.RNG.name <- RNGname
          init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                                                           1])
        }
      }
    }
    else {
      if (!is.list(inits)) {
        stop("Invalid inits")
      }
      if (length(inits) != n.chains) {
        stop("Number of initialized chains (length(inits)) != n.chains")
      }
      for (i in 1:n.chains) {
        init.values[[i]] <- inits[[i]]
        init.values[[i]]$.RNG.name <- RNGname
        init.values[[i]]$.RNG.seed <- abs(.Random.seed[i + 
                                                         1])
      }
    }
    m <- jags.model(model.file, data = data, inits = init.values, 
                    n.chains = n.chains, n.adapt = 0)
    adapt(m, n.iter = n.adapt, by = refresh, progress.bar = progress.bar, 
          end.adaptation = TRUE)
    samples <- coda.samples(model = m, variable.names = parameters.to.save, 
                            n.iter = (n.iter - n.burnin), thin = n.thin, by = refresh, 
                            progress.bar = progress.bar)
    fit <- mcmc2bugs(samples, model.file = model.file, program = "jags", 
                     DIC = DIC, DICOutput = NULL, n.iter = n.iter, n.burnin = n.burnin, 
                     n.thin = n.thin)[c("sims.array","sims.list","summary","pD","DIC")]
    out <- list(model = m, BUGSoutput = fit, parameters.to.save = parameters.to.save, 
                model.file = model.file, n.iter = n.iter, DIC = DIC)
    class(out) <- "rjags"
    return(out)
  }
  environment(jags_fit) <- environment(jags)
  
  set.seed(1234)
  
  out2 <- jags_fit(data, inits, parameters, jags_model, n.chains=nch, n.iter = ni, n.thin=nt, n.burnin=nb, DIC=TRUE, working.directory=NULL)
  
  write.csv(out2$BUGSoutput$summary, file = jobnameout)
  write.csv(analysis.par, file = paste(modelnbr,"AnalysisParameters.csv",sep="_"), row.names=F)
  save(out2,file="jagsoutput2.Rdata")
  print(gc())
}

out <- out2

